parameters:
#    web_cs_frontend.example.class: webCS\FrontendBundle\Example

services:
#    web_cs_frontend.example:
#        class: %web_cs_frontend.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
